# Generated by Django 5.2.4 on 2025-08-10 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DBProject", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gara",
            old_name="id_presidente_regione",
            new_name="presidente_regione",
        ),
        migrations.AlterField(
            model_name="allenatore",
            name="squadra",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="allenatori",
                to="DBProject.squadra",
            ),
        ),
        migrations.AlterField(
            model_name="atleta",
            name="squadra",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="atleti",
                to="DBProject.squadra",
            ),
        ),
        migrations.AlterField(
            model_name="presidentesquadra",
            name="squadra",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="presidente",
                to="DBProject.squadra",
            ),
        ),
    ]
