# Generated by Django 5.2.4 on 2025-08-12 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "DBProject",
            "0002_rename_id_presidente_regione_gara_presidente_regione_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gara",
            name="data_fine",
        ),
    ]
