# Generated by Django 5.2.4 on 2025-08-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DBProject", "0003_remove_gara_data_fine"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partecipazione",
            options={},
        ),
        migrations.RemoveField(
            model_name="partecipazione",
            name="stato_iscrizione",
        ),
        migrations.AddField(
            model_name="partecipazione",
            name="stato_partecipazione",
            field=models.CharField(
                choices=[
                    ("P", "Partecipato"),
                    ("S", "Squalificato"),
                    ("N", "Non iniziato"),
                ],
                default="N",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="partecipazione",
            name="risultato",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
