# Generated by Django 5.2.4 on 2025-08-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DBProject", "0004_alter_partecipazione_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partecipazione",
            options={
                "verbose_name": "Partecipazione",
                "verbose_name_plural": "Partecipazioni",
            },
        ),
        migrations.RemoveField(
            model_name="partecipazione",
            name="stato_partecipazione",
        ),
        migrations.AddField(
            model_name="partecipazione",
            name="stato_iscrizione",
            field=models.CharField(
                choices=[
                    ("ISCRITTO", "Iscritto"),
                    ("COMPLETATO", "Completato"),
                    ("SQUALIFICATO", "Squalificato"),
                ],
                default="ISCRITTO",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="partecipazione",
            name="risultato",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
