# Generated by Django 5.2.4 on 2025-08-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DBProject", "0005_alter_partecipazione_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gara",
            name="data_fine",
            field=models.DateField(blank=True, null=True),
        ),
    ]
