# Generated by Django 5.2.4 on 2025-08-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DBProject", "0006_gara_data_fine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partecipazione",
            name="stato_iscrizione",
            field=models.CharField(
                choices=[
                    ("ISCRITTO", "Iscritto"),
                    ("COMPLETATO", "Completato"),
                    ("SQUALIFICATO", "Squalificato"),
                    ("NON PARTITO", "Non partito"),
                ],
                default="ISCRITTO",
                max_length=20,
            ),
        ),
    ]
